name: CI Pipeline

permissions:
  contents: write  # Permet à GitHub Actions de faire des pushs dans le repo

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev, staging, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        working-directory: ./backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          pytest tests/unit tests/integration || exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

  push-to-staging:
    needs: build-and-test
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Force push dev to staging branch
        run: git push -f origin dev:staging

  build-and-deploy:
    needs: push-to-staging
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t jhoozou/project-devops:latest .

      - name: Push Docker image
        working-directory: ./backend
        run: |
          docker push jhoozou/project-devops:latest


      # Ajouter étape de déploiement vers ta plateforme cloud
      # Par exemple pour Railway avec leur CLI, Koyeb, etc.
